"use strict";
let firstName = 'Minh Tri';
let lastName = 'Dao';
let age = 21;
let isHandsome = true;
let genericType = 'genericType';
console.log(`Name: ${firstName} ${lastName}`);
console.log(`Age: ${age}`);
console.log(`Is handsome: ${isHandsome}`);
console.log(`Generic type as String: ${genericType}`);
genericType = 30;
console.log(`Generic type as Number: ${genericType}`);
